#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DETAITHUCTAP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTLX")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDethi(Dethi instance);
    partial void UpdateDethi(Dethi instance);
    partial void DeleteDethi(Dethi instance);
    partial void InsertDotthi(Dotthi instance);
    partial void UpdateDotthi(Dotthi instance);
    partial void DeleteDotthi(Dotthi instance);
    partial void InsertTaiKhoanDN(TaiKhoanDN instance);
    partial void UpdateTaiKhoanDN(TaiKhoanDN instance);
    partial void DeleteTaiKhoanDN(TaiKhoanDN instance);
    partial void InserttbBaitraloi(tbBaitraloi instance);
    partial void UpdatetbBaitraloi(tbBaitraloi instance);
    partial void DeletetbBaitraloi(tbBaitraloi instance);
    partial void InserttbCAUHOI(tbCAUHOI instance);
    partial void UpdatetbCAUHOI(tbCAUHOI instance);
    partial void DeletetbCAUHOI(tbCAUHOI instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DETAITHUCTAP.Properties.Settings.Default.QLTLXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dethi> Dethis
		{
			get
			{
				return this.GetTable<Dethi>();
			}
		}
		
		public System.Data.Linq.Table<Dotthi> Dotthis
		{
			get
			{
				return this.GetTable<Dotthi>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanDN> TaiKhoanDNs
		{
			get
			{
				return this.GetTable<TaiKhoanDN>();
			}
		}
		
		public System.Data.Linq.Table<tbBaitraloi> tbBaitralois
		{
			get
			{
				return this.GetTable<tbBaitraloi>();
			}
		}
		
		public System.Data.Linq.Table<tbCAUHOI> tbCAUHOIs
		{
			get
			{
				return this.GetTable<tbCAUHOI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dethi")]
	public partial class Dethi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madethi;
		
		private string _maloaicauhoi;
		
		private string _macauhoi;
		
		private EntitySet<Dotthi> _Dotthis;
		
		private EntityRef<tbCAUHOI> _tbCAUHOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadethiChanging(string value);
    partial void OnmadethiChanged();
    partial void OnmaloaicauhoiChanging(string value);
    partial void OnmaloaicauhoiChanged();
    partial void OnmacauhoiChanging(string value);
    partial void OnmacauhoiChanged();
    #endregion
		
		public Dethi()
		{
			this._Dotthis = new EntitySet<Dotthi>(new Action<Dotthi>(this.attach_Dotthis), new Action<Dotthi>(this.detach_Dotthis));
			this._tbCAUHOI = default(EntityRef<tbCAUHOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madethi", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madethi
		{
			get
			{
				return this._madethi;
			}
			set
			{
				if ((this._madethi != value))
				{
					this.OnmadethiChanging(value);
					this.SendPropertyChanging();
					this._madethi = value;
					this.SendPropertyChanged("madethi");
					this.OnmadethiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaicauhoi", DbType="NChar(10)")]
		public string maloaicauhoi
		{
			get
			{
				return this._maloaicauhoi;
			}
			set
			{
				if ((this._maloaicauhoi != value))
				{
					this.OnmaloaicauhoiChanging(value);
					this.SendPropertyChanging();
					this._maloaicauhoi = value;
					this.SendPropertyChanged("maloaicauhoi");
					this.OnmaloaicauhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macauhoi", DbType="NChar(10)")]
		public string macauhoi
		{
			get
			{
				return this._macauhoi;
			}
			set
			{
				if ((this._macauhoi != value))
				{
					if (this._tbCAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacauhoiChanging(value);
					this.SendPropertyChanging();
					this._macauhoi = value;
					this.SendPropertyChanged("macauhoi");
					this.OnmacauhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dethi_Dotthi", Storage="_Dotthis", ThisKey="madethi", OtherKey="madethi")]
		public EntitySet<Dotthi> Dotthis
		{
			get
			{
				return this._Dotthis;
			}
			set
			{
				this._Dotthis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCAUHOI_Dethi", Storage="_tbCAUHOI", ThisKey="macauhoi", OtherKey="macauhoi", IsForeignKey=true)]
		public tbCAUHOI tbCAUHOI
		{
			get
			{
				return this._tbCAUHOI.Entity;
			}
			set
			{
				tbCAUHOI previousValue = this._tbCAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._tbCAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCAUHOI.Entity = null;
						previousValue.Dethis.Remove(this);
					}
					this._tbCAUHOI.Entity = value;
					if ((value != null))
					{
						value.Dethis.Add(this);
						this._macauhoi = value.macauhoi;
					}
					else
					{
						this._macauhoi = default(string);
					}
					this.SendPropertyChanged("tbCAUHOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dotthis(Dotthi entity)
		{
			this.SendPropertyChanging();
			entity.Dethi = this;
		}
		
		private void detach_Dotthis(Dotthi entity)
		{
			this.SendPropertyChanging();
			entity.Dethi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dotthi")]
	public partial class Dotthi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madoithi;
		
		private string _madethi;
		
		private EntitySet<tbBaitraloi> _tbBaitralois;
		
		private EntityRef<Dethi> _Dethi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadoithiChanging(string value);
    partial void OnmadoithiChanged();
    partial void OnmadethiChanging(string value);
    partial void OnmadethiChanged();
    #endregion
		
		public Dotthi()
		{
			this._tbBaitralois = new EntitySet<tbBaitraloi>(new Action<tbBaitraloi>(this.attach_tbBaitralois), new Action<tbBaitraloi>(this.detach_tbBaitralois));
			this._Dethi = default(EntityRef<Dethi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madoithi", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madoithi
		{
			get
			{
				return this._madoithi;
			}
			set
			{
				if ((this._madoithi != value))
				{
					this.OnmadoithiChanging(value);
					this.SendPropertyChanging();
					this._madoithi = value;
					this.SendPropertyChanged("madoithi");
					this.OnmadoithiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madethi", DbType="NChar(10)")]
		public string madethi
		{
			get
			{
				return this._madethi;
			}
			set
			{
				if ((this._madethi != value))
				{
					if (this._Dethi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadethiChanging(value);
					this.SendPropertyChanging();
					this._madethi = value;
					this.SendPropertyChanged("madethi");
					this.OnmadethiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dotthi_tbBaitraloi", Storage="_tbBaitralois", ThisKey="madoithi", OtherKey="madoithi")]
		public EntitySet<tbBaitraloi> tbBaitralois
		{
			get
			{
				return this._tbBaitralois;
			}
			set
			{
				this._tbBaitralois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dethi_Dotthi", Storage="_Dethi", ThisKey="madethi", OtherKey="madethi", IsForeignKey=true)]
		public Dethi Dethi
		{
			get
			{
				return this._Dethi.Entity;
			}
			set
			{
				Dethi previousValue = this._Dethi.Entity;
				if (((previousValue != value) 
							|| (this._Dethi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dethi.Entity = null;
						previousValue.Dotthis.Remove(this);
					}
					this._Dethi.Entity = value;
					if ((value != null))
					{
						value.Dotthis.Add(this);
						this._madethi = value.madethi;
					}
					else
					{
						this._madethi = default(string);
					}
					this.SendPropertyChanged("Dethi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbBaitralois(tbBaitraloi entity)
		{
			this.SendPropertyChanging();
			entity.Dotthi = this;
		}
		
		private void detach_tbBaitralois(tbBaitraloi entity)
		{
			this.SendPropertyChanging();
			entity.Dotthi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanDN")]
	public partial class TaiKhoanDN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTS;
		
		private string _TenDangnhap;
		
		private string _Matkhau;
		
		private string _NgaySinh;
		
		private string _GioiTinh;
		
		private string _Quyen;
		
		private EntitySet<tbBaitraloi> _tbBaitralois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTSChanging(string value);
    partial void OnMaTSChanged();
    partial void OnTenDangnhapChanging(string value);
    partial void OnTenDangnhapChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public TaiKhoanDN()
		{
			this._tbBaitralois = new EntitySet<tbBaitraloi>(new Action<tbBaitraloi>(this.attach_tbBaitralois), new Action<tbBaitraloi>(this.detach_tbBaitralois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTS", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTS
		{
			get
			{
				return this._MaTS;
			}
			set
			{
				if ((this._MaTS != value))
				{
					this.OnMaTSChanging(value);
					this.SendPropertyChanging();
					this._MaTS = value;
					this.SendPropertyChanged("MaTS");
					this.OnMaTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangnhap", DbType="NVarChar(30)")]
		public string TenDangnhap
		{
			get
			{
				return this._TenDangnhap;
			}
			set
			{
				if ((this._TenDangnhap != value))
				{
					this.OnTenDangnhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangnhap = value;
					this.SendPropertyChanged("TenDangnhap");
					this.OnTenDangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(20)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NChar(20)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NChar(20)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanDN_tbBaitraloi", Storage="_tbBaitralois", ThisKey="MaTS", OtherKey="MaTS")]
		public EntitySet<tbBaitraloi> tbBaitralois
		{
			get
			{
				return this._tbBaitralois;
			}
			set
			{
				this._tbBaitralois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbBaitralois(tbBaitraloi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanDN = this;
		}
		
		private void detach_tbBaitralois(tbBaitraloi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanDN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbBaitraloi")]
	public partial class tbBaitraloi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTS;
		
		private string _macauhoi;
		
		private string _madoithi;
		
		private string _cautraloi;
		
		private int _IDtraloi;
		
		private string _Chamcau;
		
		private string _Socaudung;
		
		private string _Ketqua;
		
		private EntityRef<Dotthi> _Dotthi;
		
		private EntityRef<TaiKhoanDN> _TaiKhoanDN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTSChanging(string value);
    partial void OnMaTSChanged();
    partial void OnmacauhoiChanging(string value);
    partial void OnmacauhoiChanged();
    partial void OnmadoithiChanging(string value);
    partial void OnmadoithiChanged();
    partial void OncautraloiChanging(string value);
    partial void OncautraloiChanged();
    partial void OnIDtraloiChanging(int value);
    partial void OnIDtraloiChanged();
    partial void OnChamcauChanging(string value);
    partial void OnChamcauChanged();
    partial void OnSocaudungChanging(string value);
    partial void OnSocaudungChanged();
    partial void OnKetquaChanging(string value);
    partial void OnKetquaChanged();
    #endregion
		
		public tbBaitraloi()
		{
			this._Dotthi = default(EntityRef<Dotthi>);
			this._TaiKhoanDN = default(EntityRef<TaiKhoanDN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTS", DbType="NChar(10)")]
		public string MaTS
		{
			get
			{
				return this._MaTS;
			}
			set
			{
				if ((this._MaTS != value))
				{
					if (this._TaiKhoanDN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTSChanging(value);
					this.SendPropertyChanging();
					this._MaTS = value;
					this.SendPropertyChanged("MaTS");
					this.OnMaTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macauhoi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string macauhoi
		{
			get
			{
				return this._macauhoi;
			}
			set
			{
				if ((this._macauhoi != value))
				{
					this.OnmacauhoiChanging(value);
					this.SendPropertyChanging();
					this._macauhoi = value;
					this.SendPropertyChanged("macauhoi");
					this.OnmacauhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madoithi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string madoithi
		{
			get
			{
				return this._madoithi;
			}
			set
			{
				if ((this._madoithi != value))
				{
					if (this._Dotthi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadoithiChanging(value);
					this.SendPropertyChanging();
					this._madoithi = value;
					this.SendPropertyChanged("madoithi");
					this.OnmadoithiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cautraloi", DbType="NVarChar(50)")]
		public string cautraloi
		{
			get
			{
				return this._cautraloi;
			}
			set
			{
				if ((this._cautraloi != value))
				{
					this.OncautraloiChanging(value);
					this.SendPropertyChanging();
					this._cautraloi = value;
					this.SendPropertyChanged("cautraloi");
					this.OncautraloiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDtraloi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDtraloi
		{
			get
			{
				return this._IDtraloi;
			}
			set
			{
				if ((this._IDtraloi != value))
				{
					this.OnIDtraloiChanging(value);
					this.SendPropertyChanging();
					this._IDtraloi = value;
					this.SendPropertyChanged("IDtraloi");
					this.OnIDtraloiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chamcau", DbType="NChar(10)")]
		public string Chamcau
		{
			get
			{
				return this._Chamcau;
			}
			set
			{
				if ((this._Chamcau != value))
				{
					this.OnChamcauChanging(value);
					this.SendPropertyChanging();
					this._Chamcau = value;
					this.SendPropertyChanged("Chamcau");
					this.OnChamcauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Socaudung", DbType="NChar(10)")]
		public string Socaudung
		{
			get
			{
				return this._Socaudung;
			}
			set
			{
				if ((this._Socaudung != value))
				{
					this.OnSocaudungChanging(value);
					this.SendPropertyChanging();
					this._Socaudung = value;
					this.SendPropertyChanged("Socaudung");
					this.OnSocaudungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ketqua", DbType="NChar(10)")]
		public string Ketqua
		{
			get
			{
				return this._Ketqua;
			}
			set
			{
				if ((this._Ketqua != value))
				{
					this.OnKetquaChanging(value);
					this.SendPropertyChanging();
					this._Ketqua = value;
					this.SendPropertyChanged("Ketqua");
					this.OnKetquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dotthi_tbBaitraloi", Storage="_Dotthi", ThisKey="madoithi", OtherKey="madoithi", IsForeignKey=true)]
		public Dotthi Dotthi
		{
			get
			{
				return this._Dotthi.Entity;
			}
			set
			{
				Dotthi previousValue = this._Dotthi.Entity;
				if (((previousValue != value) 
							|| (this._Dotthi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dotthi.Entity = null;
						previousValue.tbBaitralois.Remove(this);
					}
					this._Dotthi.Entity = value;
					if ((value != null))
					{
						value.tbBaitralois.Add(this);
						this._madoithi = value.madoithi;
					}
					else
					{
						this._madoithi = default(string);
					}
					this.SendPropertyChanged("Dotthi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanDN_tbBaitraloi", Storage="_TaiKhoanDN", ThisKey="MaTS", OtherKey="MaTS", IsForeignKey=true)]
		public TaiKhoanDN TaiKhoanDN
		{
			get
			{
				return this._TaiKhoanDN.Entity;
			}
			set
			{
				TaiKhoanDN previousValue = this._TaiKhoanDN.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoanDN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoanDN.Entity = null;
						previousValue.tbBaitralois.Remove(this);
					}
					this._TaiKhoanDN.Entity = value;
					if ((value != null))
					{
						value.tbBaitralois.Add(this);
						this._MaTS = value.MaTS;
					}
					else
					{
						this._MaTS = default(string);
					}
					this.SendPropertyChanged("TaiKhoanDN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCAUHOI")]
	public partial class tbCAUHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macauhoi;
		
		private string _cauhoi;
		
		private string _cau_a;
		
		private string _cau_b;
		
		private string _cau_c;
		
		private string _cau_d;
		
		private string _dapan;
		
		private string _maloaicauhoi;
		
		private EntitySet<Dethi> _Dethis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacauhoiChanging(string value);
    partial void OnmacauhoiChanged();
    partial void OncauhoiChanging(string value);
    partial void OncauhoiChanged();
    partial void Oncau_aChanging(string value);
    partial void Oncau_aChanged();
    partial void Oncau_bChanging(string value);
    partial void Oncau_bChanged();
    partial void Oncau_cChanging(string value);
    partial void Oncau_cChanged();
    partial void Oncau_dChanging(string value);
    partial void Oncau_dChanged();
    partial void OndapanChanging(string value);
    partial void OndapanChanged();
    partial void OnmaloaicauhoiChanging(string value);
    partial void OnmaloaicauhoiChanged();
    #endregion
		
		public tbCAUHOI()
		{
			this._Dethis = new EntitySet<Dethi>(new Action<Dethi>(this.attach_Dethis), new Action<Dethi>(this.detach_Dethis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macauhoi", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macauhoi
		{
			get
			{
				return this._macauhoi;
			}
			set
			{
				if ((this._macauhoi != value))
				{
					this.OnmacauhoiChanging(value);
					this.SendPropertyChanging();
					this._macauhoi = value;
					this.SendPropertyChanged("macauhoi");
					this.OnmacauhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cauhoi", DbType="NVarChar(MAX)")]
		public string cauhoi
		{
			get
			{
				return this._cauhoi;
			}
			set
			{
				if ((this._cauhoi != value))
				{
					this.OncauhoiChanging(value);
					this.SendPropertyChanging();
					this._cauhoi = value;
					this.SendPropertyChanged("cauhoi");
					this.OncauhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cau a]", Storage="_cau_a", DbType="NVarChar(MAX)")]
		public string cau_a
		{
			get
			{
				return this._cau_a;
			}
			set
			{
				if ((this._cau_a != value))
				{
					this.Oncau_aChanging(value);
					this.SendPropertyChanging();
					this._cau_a = value;
					this.SendPropertyChanged("cau_a");
					this.Oncau_aChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cau b]", Storage="_cau_b", DbType="NVarChar(MAX)")]
		public string cau_b
		{
			get
			{
				return this._cau_b;
			}
			set
			{
				if ((this._cau_b != value))
				{
					this.Oncau_bChanging(value);
					this.SendPropertyChanging();
					this._cau_b = value;
					this.SendPropertyChanged("cau_b");
					this.Oncau_bChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cau c]", Storage="_cau_c", DbType="NVarChar(MAX)")]
		public string cau_c
		{
			get
			{
				return this._cau_c;
			}
			set
			{
				if ((this._cau_c != value))
				{
					this.Oncau_cChanging(value);
					this.SendPropertyChanging();
					this._cau_c = value;
					this.SendPropertyChanged("cau_c");
					this.Oncau_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cau d]", Storage="_cau_d", DbType="NVarChar(MAX)")]
		public string cau_d
		{
			get
			{
				return this._cau_d;
			}
			set
			{
				if ((this._cau_d != value))
				{
					this.Oncau_dChanging(value);
					this.SendPropertyChanging();
					this._cau_d = value;
					this.SendPropertyChanged("cau_d");
					this.Oncau_dChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dapan", DbType="NChar(10)")]
		public string dapan
		{
			get
			{
				return this._dapan;
			}
			set
			{
				if ((this._dapan != value))
				{
					this.OndapanChanging(value);
					this.SendPropertyChanging();
					this._dapan = value;
					this.SendPropertyChanged("dapan");
					this.OndapanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaicauhoi", DbType="NChar(10)")]
		public string maloaicauhoi
		{
			get
			{
				return this._maloaicauhoi;
			}
			set
			{
				if ((this._maloaicauhoi != value))
				{
					this.OnmaloaicauhoiChanging(value);
					this.SendPropertyChanging();
					this._maloaicauhoi = value;
					this.SendPropertyChanged("maloaicauhoi");
					this.OnmaloaicauhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCAUHOI_Dethi", Storage="_Dethis", ThisKey="macauhoi", OtherKey="macauhoi")]
		public EntitySet<Dethi> Dethis
		{
			get
			{
				return this._Dethis;
			}
			set
			{
				this._Dethis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dethis(Dethi entity)
		{
			this.SendPropertyChanging();
			entity.tbCAUHOI = this;
		}
		
		private void detach_Dethis(Dethi entity)
		{
			this.SendPropertyChanging();
			entity.tbCAUHOI = null;
		}
	}
}
#pragma warning restore 1591
